name: ci

on:
  release:
    types: [created]

env:
  IMAGE_NAME: ${{ vars.DOCKERHUB_USERNAME }}/ermes-redis

jobs:
  docker:
    runs-on: ubuntu-latest
    if : contains(github.ref, 'api-v')
    steps:
      - name: Extract version
        run: |
          echo "VERSION=$(echo ${{ github.ref }} | sed 's/refs\/tags\/api-v//')" >> $GITHUB_ENV

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:${{ env.VERSION }}
            ${{ env.IMAGE_NAME }}:latest
      
