name: test

on:
  push:
    paths:
      - 'packages/go/**'
      - '.github/workflows/test.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: ["1.22.x"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build . -t redis-image

      - name: Run Docker container
        run: docker run -p 6379:6379 redis-image
  
      - name: Setup Go ${{ matrix.go-version }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}
      # You can test your matrix by printing the current Go version
      - name: Display Go version
        run: go version

      - name: Install dependencies
        working-directory: ./test
        run: go get .

      - name: Test with the Go CLI and run coverage
        working-directory: ./test
        run: go test ./... -coverprofile=coverage.out -covermode=atomic
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: ./test/coverage.out
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
